### ISSUE TITLE
Language and currency in link URLs

### ISSUE THREAD

**Issue by lloyd-borrett** [numinix/google_product_search_feeder_public#12]
G'day,

My product feed is including &language=en and &currency=AUD in the link URL.

Given that these are the default currency and language for the website, shouldn't they be left out?

After all, the effect is to create a new set URLs at Google, which are different to the URLs in the sitemap feed and in the canonical links. These new URLs will be redirected to the standard URL without these options anyway, but doing so weakens their effectiveness.

I would have thought the language and currency values should only be included if the feed is being generated for a language or country other than the default one.

Best regards, Lloyd Borrett.

**Comment by jefflew** [comment]
You can turn off including the language and currency in the configuration
for the plugin.

On Fri, Apr 24, 2015 at 4:56 PM, Lloyd Borrett <notifications@github.com>
wrote:

> G'day,
>
> My product feed is including &language=en and &currency=AUD in the link
> URL.
>
> Given that these are the default currency and language for the website,
> shouldn't they be left out?
>
> After all, the effect is to create a new set URLs at Google, which are
> different to the URLs in the sitemap feed and in the canonical links. These
> new URLs will be redirected to the standard URL without these options
> anyway, but doing so weakens their effectiveness.
>
> I would have thought the language and currency values should only be
> included if the feed is being generated for a language or country other
> than the default one.
>
> Best regards, Lloyd Borrett.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/google_product_search_feeder_public/issues/12>
> .
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by lloyd-borrett** [comment]
Thanks Jeff,

I thought that would also remove the currency from the price, but it doesn't. Maybe a change to the description could make this clearer for people.

Now I just have to figure out why Google is reporting disapprovals for 25 items due to policy violations.

Best regards, Lloyd.

**Comment by jefflew** [comment]
We've made this be able to be passed through the URL params in v3.4.0
