### ISSUE TITLE
Encoding Errors

### ISSUE THREAD

**Issue by lloyd-borrett** [numinix/google_product_search_feeder_public#3]
Script stops with encoding error if it encounters a HTML entity e.g. &deg; or &copy; in the product description.

**Comment by lloyd-borrett** [comment]
Sorry, that's a HTML entity in text form like & c o p y ;

**Comment by jefflew** [comment]
Hi Lloyd,

Please try turning on the Advanced XML Sanitizer in the configuration.

**Comment by lloyd-borrett** [comment]
That seems to have done the trick. Thanks Jeff.
