### ISSUE TITLE
Strip out spaces

### ISSUE THREAD

**Issue by lloyd-borrett** [numinix/google_product_search_feeder_public#4]
In striping out HTML from descriptions, you end up leaving lots of multiple spaces. More of the actual description text could be present on large descriptions if you were to strip out multiple spaces before truncating the description to the max character limit.

Plus descriptions that don't exceed the limit would look better if the extra spaces were removed.

**Comment by jefflew** [comment]
Will be added in v3.3.6 (unreleased)
