### ISSUE TITLE
EAN and COLOR

### ISSUE THREAD

**Issue by lloyd-borrett** [numinix/google_product_search_feeder_public#5]
Google Merchant Center is reporting feed errors.
Problem products have g:color and g:ean values being generated. 
e.g.
   <g:color><![CDATA[black]]></g:color>
   <g:ean><![CDATA[oxygen clean, nitrox ready valve?]]></g:ean>
That ean text is related to attributes for the product.
Configuration has UPC/ISBN/EAN set to false.
We're not using Numinix Product Fields.

**Comment by jefflew** [comment]
That setting only controls the optional fields that can be added to
products via Numinix Product Fields.  The plugin supports using the Zen
Cart default attribute system to create various attributes in Google.

The EAN field on your site is not being used in a typical manner.  An EAN
is usually a 13 digit alphanumerical string.

On Mon, Apr 13, 2015 at 9:14 AM, Lloyd Borrett <notifications@github.com>
wrote:

> Google Merchant Center is reporting feed errors.
> Problem products have g:color and g:ean values being generated.
> e.g.
> <![CDATA[black]]>/g:color
> <![CDATA[oxygen clean, nitrox ready valve?]]>/g:ean
> That ean text is related to attributes for the product.
> Configuration has UPC/ISBN/EAN set to false.
> We're not using Numinix Product Fields.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/google_product_search_feeder_public/issues/5>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by lloyd-borrett** [comment]
I'm not aware that we have color and ean fields at all. We don't have Numinix Product Fields installed.

About 25 products in some 1800 are having an ean value made up from attributes values added to the feed. Google reports Invalid GTIN value.

Even more products are having a g:color field added, again using an attribute value. This shouldn't be happening. But Google isn't finding a problem with the actual color values being used.

**Comment by jefflew** [comment]
If you have an option name set as "EAN" or "ean" it will use that as the
g:ean element in the feed.

                                case ($options_name == 'ean'):
                                  $custom_fields[] = array('name' => 'ean',
'value' => strtolower($options_values_name));
                                  $unique_identifiers++;
                                  $ean_set = true;
                                  break;

Any attribute containing the word "Color" or "Colour" will activate the
g:color element in the feed.

                                case (stripos($options_name, 'color') !==
FALSE):
                                case (stripos($options_name, 'colour') !==
FALSE):
                                  $custom_fields[] = array('name' =>
'color', 'value' => strtolower($options_values_name));
                                  $variants_title .= ' ' .
$options_values_name;
                                  $variant = true;
                                  break;

On Mon, Apr 13, 2015 at 9:30 AM, Lloyd Borrett <notifications@github.com>
wrote:

> I'm not aware that we have color and ean fields at all. We don't have
> Numinix Product Fields installed.
>
> About 25 products in some 1800 are having an ean value made up from
> attributes values added to the feed. Google reports Invalid GTIN value.
>
> Even more products are having a g:color field added, again using an
> attribute value. This shouldn't be happening. But Google isn't finding a
> problem with the actual color values being used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/google_product_search_feeder_public/issues/5#issuecomment-92418561>
> .
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by lloyd-borrett** [comment]
We don't have an option name set as EAN or ean. On the problem products we do have an option value of Oxygen Clean. I suspect you're picking up the ean on the end of Clean. That shouldn't happen.

We have plenty of products with multiple colour attributes set. But in every case you're only picking up and using one colour value. What's the point of that? It would make sense if you were to output every colour choice, but the feed specification doesn't allow that. In our case the field would get very long.

The feed spec is very specific about what characters are allowed in the color field. For example, If you're using XML, you must represent the '/' with & # 4 7 ;. We have / in the fields you're outputting and it's not being handled as per the spec.

Suggest you need to change the handling of the color values to conform closer to the spec.

Also suggest you should have configuration options to allow us to override the generation of ean and color fields.

**Comment by jefflew** [comment]
Hi Lloyd,

I've checked your order history and do not see that you have ever purchased
a license for our Google Product Search Feeder plugin.  I just want to make
sure we're talking about the same plugin and not our free version, Google
Merchant Center Feeder.

I've reviewed the code in GPSF and it does require an exact match for the
EAN.

The color attribute is output once per variation.  If you sell multiple
variants, then it will create a new item for each variant and a different
color will be used for each.  This may only be the case when using a
variant management plugin such as Stock by Attributes of Numinix Product
Variants Inventory Manager.

We'll look into adding the XML sanitizer function to the attribute outputs
such as Color.

On Mon, Apr 13, 2015 at 10:15 AM, Lloyd Borrett <notifications@github.com>
wrote:

> We don't have an option name set as EAN or ean. On the problem products we
> do have an option value of Oxygen Clean. I suspect you're picking up the
> ean on the end of Clean. That shouldn't happen.
>
> We have plenty of products with multiple colour attributes set. But in
> every case you're only picking up and using one colour value. What's the
> point of that? It would make sense if you were to output every colour
> choice, but the feed specification doesn't allow that. In our case the
> field would get very long.
>
> The feed spec is very specific about what characters are allowed in the
> color field. For example, If you're using XML, you must represent the '/'
> with & # 4 7 ;. We have / in the fields you're outputting and it's not
> being handled as per the spec.
>
> Suggest you need to change the handling of the color values to conform
> closer to the spec.
>
> Also suggest you should have configuration options to allow us to override
> the generation of ean and color fields.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/google_product_search_feeder_public/issues/5#issuecomment-92429493>
> .
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by jefflew** [comment]
Correction, the sanitizer is already used on the option value name:

$options_values_name =
$googleProducts->googleProducts_xml_sanitizer($options->fields['products_options_values_name']);

On Mon, Apr 13, 2015 at 10:21 AM, Jeff Lew <jlew@numinix.com> wrote:

> Hi Lloyd,
>
> I've checked your order history and do not see that you have ever
> purchased a license for our Google Product Search Feeder plugin.  I just
> want to make sure we're talking about the same plugin and not our free
> version, Google Merchant Center Feeder.
>
> I've reviewed the code in GPSF and it does require an exact match for the
> EAN.
>
> The color attribute is output once per variation.  If you sell multiple
> variants, then it will create a new item for each variant and a different
> color will be used for each.  This may only be the case when using a
> variant management plugin such as Stock by Attributes of Numinix Product
> Variants Inventory Manager.
>
> We'll look into adding the XML sanitizer function to the attribute outputs
> such as Color.
>
> On Mon, Apr 13, 2015 at 10:15 AM, Lloyd Borrett <notifications@github.com>
> wrote:
>
>> We don't have an option name set as EAN or ean. On the problem products
>> we do have an option value of Oxygen Clean. I suspect you're picking up the
>> ean on the end of Clean. That shouldn't happen.
>>
>> We have plenty of products with multiple colour attributes set. But in
>> every case you're only picking up and using one colour value. What's the
>> point of that? It would make sense if you were to output every colour
>> choice, but the feed specification doesn't allow that. In our case the
>> field would get very long.
>>
>> The feed spec is very specific about what characters are allowed in the
>> color field. For example, If you're using XML, you must represent the '/'
>> with & # 4 7 ;. We have / in the fields you're outputting and it's not
>> being handled as per the spec.
>>
>> Suggest you need to change the handling of the color values to conform
>> closer to the spec.
>>
>> Also suggest you should have configuration options to allow us to
>> override the generation of ean and color fields.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/numinix/google_product_search_feeder_public/issues/5#issuecomment-92429493>
>> .
>>
>
>
>
> --
>
>  *Jeff Lew*
> President
>
> *Phone:* 1-855-686-4649 Ext 700
> *Email/Gchat:* jlew@numinix.com
> *Skype:* numinix
>  [image: Numinix] <http://www.numinix.com/>
>
>  [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
> <http://twitter.com/numinix> [image: Google+]
> <https://plus.google.com/+Numinix> [image: Instagram]
> <http://instagram.com/numinixwebdev> [image: Pinterest]
> <http://www.pinterest.com/numinix> [image: Blog]
> <http://www.numinix.com/blog/?feed=rss2>
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by lloyd-borrett** [comment]
Our Google Product Search Feeder plugin was purchased and installed for us by Cindy Merkin, lat9

Well the EAN exact match isn't working. It seems obvious what is happening to cause us to get an ean field output. It's happening on the products where we have the Oxygen Clean value. We don't want an ean field to be output.

Okay, I get why the color field is needed when using a variant management plugin. But we're not using one and we need some way to turn this action off. I'm sure we wouldn't be the only ones needing this.

**Comment by jefflew** [comment]
Lloyd,

Please contact me at jlew @ numinix.com.  It sounds like you are using an older version, hence the bugs.  I do see that Cindy purchased a license in early 2014.  However, it was licensed to a specific domain and I'd like to verify that domain is yours.

**Comment by lloyd-borrett** [comment]
domain scubadoctor.com.au
Cindy updated us to the latest version earlier today which resolved some other issues we were having.
But these ones still remain.

If the sanitizer is already being used properly then we shouldn't get 
<g:color><![CDATA[clear / yellow]]></g:color>
in our feed?

**Comment by jefflew** [comment]
Yes, that's the correct domain.

Perhaps it's not an XML issue but specific to the color field.  We'll have
a look at that.  Is it generating a warning or an error?

**Comment by lloyd-borrett** [comment]
As Google says...

What not to include:
Limit the number of colours submitted to three values.
If you're using XML, you must represent the '/' with &#47;
Colour values that contain numbers (e.g. '0 2 4 6 8')
Colour values that contain non-alphanumerical characters (e.g. '#fff000')
Single-letter colour values (e.g. 'G') in Latin-based languages. Single-letter colour values in Chinese-Japanese-Korean languages (e.g. '红') are acceptable.
Colour values that reference the product or product image (e.g. 'see image')
Descriptive values that are not actually valid colour names (e.g. multicolour, various, variety, see image, N/A)
Long colour values exceeding 40 characters
Long colour values that are aggregates of several other colours (e.g. RedPinkBlue). Instead:
If you are trying to indicate multiple colours for a single item (not product variants), specify a primary colour, optionally followed by at most two secondary colours, separated by a '/'. Here replace RedPinkBlue with Red/Pink/Blue
If you are trying to indicate multiple colours for multiple similar items (product variants), submit these as separate products each with the same item group ID and a different colour value.

**Comment by lat9** [comment]
The g:ean issue (where it's incorrectly finding a match on an option named 'Oxygen Cl**ean**') is corrected by changing line 209 of /google_product_search.php, changing the 'ean' to ' ean ' (i.e. adding spaces before and after the "token").

**Comment by jefflew** [comment]
That solution will work for anyone not using EAN, but will break that
functionality (since no space will exist at the start of the option name).
We'll have to update our strapos function to use preg_match and a regex for
full word matching (\b).

**Comment by lat9** [comment]
I realized that after I made the change and thought about it a bit.  Perhaps that list of attributes should fall into two classes (1) stand-alone, i.e. the option name must equal the field name and (2) the field name is part of the option name.

**Comment by jefflew** [comment]
In the strapos() function, can you please try this:

		  /*
      	  if (stripos($haystack, $needle) !== FALSE) {
      	  	return $key;
		  }
		  */
		  if (preg_match('/\b' . $needle . '\b/', $haystack) == 1) {
		  	return $key;
		  }

AND:

	  	//return stripos($haystack, $needles, (int)$offset);
	  	return preg_match('/\b' . $needle . '\b/', $haystack);

**Comment by jefflew** [comment]
Sorry, the second should be:
	  	//return stripos($haystack, $needles, (int)$offset);
	  	return preg_match('/\b' . $needles . '\b/', substr($haystack, (int)$offset));

**Comment by jefflew** [comment]
See v3.4.0
