### ISSUE TITLE
Shipping Weight Issue

### ISSUE THREAD

**Issue by lloyd-borrett** [numinix/google_product_search_feeder_public#6]
If the shipping weight hasn't been set then a shipping weight value is still output, eg 0 kg.

A better default would be to not output the shipping weight if no value is set.

**Comment by jefflew** [comment]
Does your website use database caching?  If so the setting may not take
immediate affect.

The shipping weight is only used if activated:

      if(GOOGLE_PRODUCTS_WEIGHT == 'true' &&
$products->fields['products_weight'] != '') {
        //$item->appendChild($dom->createElement('g:weight',
$products->fields['products_weight'] . ' ' . GOOGLE_PRODUCTS_UNITS));
        $xmlWriter->writeElement('g:shipping_weight',
$products->fields['products_weight'] . ' ' . str_replace(array('pounds',
'kilograms'), array('lb', 'kg'), GOOGLE_PRODUCTS_UNITS));
      }

On Mon, Apr 13, 2015 at 9:19 AM, Lloyd Borrett <notifications@github.com>
wrote:

> If the shipping weight hasn't been set then a shipping weight value is
> still output, eg 0 kg.
>
> A better default would be to not output the shipping weight if no value is
> set.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/google_product_search_feeder_public/issues/6>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by lloyd-borrett** [comment]
Jeff, we'd like the shipping weight value output if we have a weight value set. But if there is no weight value set, i.e. if it's null or empty, then it shouldn't be output. It just needs an appropriate test in that code.

**Comment by jefflew** [comment]
Try changing the condition to

&& $products->fields['products_weight'] > 0

Does that solve your issue?

On Mon, Apr 13, 2015 at 9:35 AM, Lloyd Borrett <notifications@github.com>
wrote:

> Jeff, we'd like the shipping weight value output if we have a weight value
> set. But if there is no weight value set, i.e. if it's null or empty, then
> it shouldn't be output. It just needs an appropriate test in that code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/google_product_search_feeder_public/issues/6#issuecomment-92419877>
> .
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by jefflew** [comment]
Done in v3.3.4
