### ISSUE TITLE
Multiple Countries

### ISSUE THREAD

**Issue by lloyd-borrett** [numinix/google_product_search_feeder_public#8]
Google Merchant Center supports having separate unique feeds for each of multiple countries. How can this be automatically supported?

**Comment by jefflew** [comment]
The feed has been tested to work in the US and UK.

**Comment by lloyd-borrett** [comment]
But can we automatically generate and upload two or three feeds each time, e.g. ones for AU, US and UK.

**Comment by jefflew** [comment]
Do you mean for different currency and language?  Yes, those could be created as URL parameters in a future version of the plugin.

**Comment by lloyd-borrett** [comment]
Yes I mean for two or more feeds being created, each with the prices, language and other settings for the targeted country.

**Comment by jefflew** [comment]
See 3.4.0
